version: ~> 1.0
language: python
dist: bionic
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install "pytest>=5.1" "mock>=4" "pytest-mock>=2" pytest-cov codecov
script: ./_run-tests.py
before_cache: rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
